CreacionDeSistemasDeMenus
EsotericEdgeGames/Royal-Clicker pull request #21
Opened 2024-08-27 05:18 UTC by TotoroIsBack

Bueno ahora creo que hice todo bien sobre esta "actualizacion"
lo que hice fue agregar varias escenas y poner el codigo para que al apretar los botones correspondientes cambie a la escena elegida.

2024-08-27 14:06 UTC, Ale2301 requested changes
La escena "menu.tscn" no esta es la principal, por ende al ejecutar la escena se llama directamente a la pantalla de gameplay.

El botón "play" debería llevar al modo online

El botón "práctica" debería llevar a la pantalla con el botón que tenemos ahora, es decir, 1 jugador

2024-08-27 14:45 UTC, TotoroIsBack commented
> La escena "menu.tscn" no esta es la principal, por ende al ejecutar la escena se llama directamente a la pantalla de gameplay.
> 
> El botón "play" debería llevar al modo online
> 
> El botón "práctica" debería llevar a la pantalla con el botón que tenemos ahora, es decir, 1 jugador

osea con el boton play tendria que llevar a la escena donde encontrar los servers masomenos, con el que va a la practica seria el juego que tenemos ahora no?

2024-08-27 16:13 UTC, Ale2301 commented
> > La escena "menu.tscn" no esta es la principal, por ende al ejecutar la escena se llama directamente a la pantalla de gameplay.
> > El botón "play" debería llevar al modo online
> > El botón "práctica" debería llevar a la pantalla con el botón que tenemos ahora, es decir, 1 jugador
> 
> osea con el boton play tendria que llevar a la escena donde encontrar los servers masomenos, con el que va a la practica seria el juego que tenemos ahora no?

Si. Dibuja un poco la escena de los servers, lo importante es que los botones estén, el flujo se mantenga, y no haya un lugar "lockeado"

2024-08-27 17:36 UTC, Ale2301 reviewed
El código funciona correctamente, pero deben hacerse varios cambios antes de

2024-08-27 17:36 UTC, Ale2301 commented on Menù.gd
> +
Ninguna de estas funciones es un método de godot, por lo que deben estar en español utilizando snake_case

2024-08-27 17:36 UTC, Ale2301 commented on ServerList.gd
> +func _on_menu_pressed():
Mismo caso que arriba

2024-08-27 17:36 UTC, Ale2301 commented on node_3d.gd
> +func _on_menu_pressed():
Mismo caso que arriba, esta function debe estar en español

2024-08-27 17:36 UTC, Ale2301 commented on node_3d.tscn
> +[node name="Clicker" type="Button" parent="Control"]
Este nombre se cambio por algo en especial?

2024-08-27 17:36 UTC, Ale2301 commented on node_3d.gd
> +
Ojo con dejar marcas en código donde no tocaste nada. Esta línea me marca que la editaste (Posiblemente porque agregaste o quitaste algún espacio en blanco). Este comentario es informativo, intentemos evitar esto

2024-08-27 17:40 UTC, TotoroIsBack commented on node_3d.gd
> +
yo la verdad no toque nada en el proyecto no me aparece eso

2024-08-27 17:41 UTC, TotoroIsBack commented on node_3d.tscn
> +[node name="Clicker" type="Button" parent="Control"]
si por tema de comodidad y para evitar confusiones en algun futuro

2024-08-27 17:42 UTC, TotoroIsBack commented on Menù.gd
> +
no entiendo porque no es un metodo de godot

2024-08-29 00:43 UTC, Ale2301 reviewed
Aprobado todo el código. Pero hay un error grave que no había visto hasta ahora (Y menos mal que lo hice). El texto de "Royal Clicker" se puede editar desde el build, y al ser el título, no debería de serlo

2024-08-29 21:58 UTC, Ale2301 approved these changes
Aprobado, corregi los conflictos y mergea

2024-08-29 22:03 UTC, merged