Cd boton
EsotericEdgeGames/Royal-Clicker pull request #29
Opened 2024-09-11 18:11 UTC by JuanSebas572

Se añade un cooldown de 0.20 segundos al boton

2024-09-11 21:53 UTC, Ale2301 requested changes
¿Por qué creaste una copia de la escena principal del juego para hacer esto? No cumple el AC, no puedo corregirlo

2024-09-16 21:31 UTC, Ale2301 requested changes
A pesar del código funcionar, tiene muchas cosas muertas o extrañas. Además, no está actualizado a la master, con lo cual para probarlo tuve que hacer mi propia actualización local. Corregir y avisar

2024-09-16 21:31 UTC, Ale2301 commented on Control.gd
Esto NO esta bien. Este archivo no esta en la carpeta correspondiente, adicional a que NO HACE NADA. Eliminalo.

2024-09-16 21:31 UTC, Ale2301 commented on Escenas/node_3d.tscn
> +offset_bottom = 108.0
Que fue lo que editaste de la escena para que estén presentes estos cambios?

2024-09-16 21:31 UTC, Ale2301 commented on Scripts/node_3d.gd
> +			tiempo_actual = 0.0  # Reiniciar el tiempo acumulado
Se mezclan las lógicas, es un poco difícil de leer. Línea 15-16-17-18-19 gestiona el CPS, línea 20 empieza a gestionar algo totalmente diferente. Move todo esto dentro de una función para que los demás no se rompan la cabeza en el futuro

2024-09-16 21:31 UTC, Ale2301 commented on Scripts/node_3d.gd
> +# Función que se ejecuta cada vez que se hace click en el botón
Por qué editaste este comentario?

2024-09-16 21:31 UTC, Ale2301 commented on Scripts/node_3d.gd
> +	boton.pressed.connect(boton_presionado)  # Conectar el botón al evento de presionado
Esto no esta mal, pero me hace ruido. ¿No se puede conectar el botón al evento de presionado desde fuera del código (Es decir, la escena)? Si se puede hacelo, sino ampliame

2024-09-16 21:31 UTC, Ale2301 commented on control.tscn
Esto NO esta bien. Este archivo no esta en la carpeta correspondiente, adicional a que NO HACE NADA. Eliminalo.

2024-09-16 22:04 UTC, JuanSebas572 commented on Scripts/node_3d.gd
> +	boton.pressed.connect(boton_presionado)  # Conectar el botón al evento de presionado
no estaria encontrando una forma de hacerlo

2024-09-17 10:48 UTC, Ale2301 commented on SistemaDePerks.gd
> +	scroll.add_child(vbox)  # Añade el VBox al contenedor de desplazamiento
Hay una razón por lo que los commits se separan. Al ser un proyecto chico, yo ya se que es esto y por qué sale como cambio. Pero aún así no debería. Siempre que tengas que actualizar (git pull origin master) hacelo en un commit aparte

2024-09-17 10:48 UTC, Ale2301 commented on Scripts/node_3d.gd
> +# Función que se ejecuta cuando se hace click en el botón.
Todavía no me respondiste por qué este editaste este comentario

2024-09-17 11:12 UTC, JuanSebas572 commented on Scripts/node_3d.gd
> +# Función que se ejecuta cuando se hace click en el botón.
ale no te voy a mentir, como mi asistente en ese codigo fue una ia me cambio ese comentario, y la verdad lo pase por alto

2024-09-19 18:45 UTC, Ale2301 requested changes
![image](https://github.com/user-attachments/assets/83d1c581-6de5-4d24-b1bc-fef6bdfd0948)
No lo revisaste antes de mandarlo...

2024-09-21 02:05 UTC, Ale2301 approved these changes

2024-09-24 00:52 UTC, merged