SistemaDeRedondeosDeNumeros
EsotericEdgeGames/Royal-Clicker pull request #32
Opened 2024-09-20 01:32 UTC by TotoroIsBack

acá se le agrego un sistema de redondeos con un código simple y legible, también se le puso un código para verificar que el código funciona.

2024-09-20 03:50 UTC, Ale2301 requested changes
Primero, mis felicitaciones. El algoritmo funciona, y hacer un algoritmo es algo difícil. Lamentablemente mi trabajo acá no es ser un tipazo, así que tengo que pedirte algunos cambios. Lo del script es charlable

2024-09-20 03:50 UTC, Ale2301 commented on Cps.gd
No entiendo, que hace este archivo acá?

2024-09-20 03:50 UTC, Ale2301 commented on Escenas/node_3d.tscn
> +
Por que hay un nodo nuevo creado?

2024-09-20 03:50 UTC, Ale2301 commented on Scripts/node_3d.gd
> +
Excelente solución. Te dejo una sugerencia sobre como quedaría un poco más "elegante". Podemos charlarlo por Discord si consideras lo contrario
```suggestion
const SUFIJOS = {
		1000000000000000.0: "C",
		1000000000000.0: "T",
		1000000000.0: "B",
		1000000.0: "M",
		1000.0: "K"
	}
	func _sistema_de_redondeo_de_numeros(value: int) -> String:
	for limite in SUFIJOS.keys():
		if (value >= int(limite)):
			return str(floor(value / limite * 100) / 100) + SUFIJOS[limite]
	return str(value)

func _ready():
	var numbers = [999, 999999, 1500000, 2500000000, 12500000, 2600000000000000, 3800000000000]
	for clicks in numbers:
		print(_sistema_de_redondeo_de_numeros(clicks))
```

(Lo copie de mi godot. No lo commitees desde acá, quizás esté mal indentado)

2024-09-20 03:56 UTC, TotoroIsBack commented on Escenas/node_3d.tscn
> +
yo eso no lo toque que onda
yo no hice nada de label

2024-09-20 03:59 UTC, TotoroIsBack commented on Scripts/node_3d.gd
> +
no se si vos ves que esta mejor ponerlo asi esta bien

2024-09-20 04:00 UTC, Ale2301 commented on Escenas/node_3d.tscn
> +
Eliminalo

2024-09-20 04:01 UTC, Ale2301 commented on Scripts/node_3d.gd
> +
Podes preguntarle a los demás que opinan. Es algo medio subjetivo realmente

2024-09-20 04:02 UTC, TotoroIsBack commented on Escenas/node_3d.tscn
> +
en donde si no existe
en las escenas que tengo abiertas no hay nada, solo toque la del practice

2024-09-20 04:04 UTC, TotoroIsBack commented on Escenas/node_3d.tscn
> +
ya lo encontre, yo no habia tocado nada de label que onda

2024-09-21 01:56 UTC, Ale2301 approved these changes

2024-09-21 02:06 UTC, merged